language: node_js
node_js:
  - "6.1"
before_install:
  - npm install -g bower grunt-cli #protractor
  # - webdriver-manager update
install:
  - npm install
script:
  - grunt lint
  - grunt test:unit:development
  - grunt test:unit:production
  # - grunt test:e2e --ci
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
addons:
  sauce_connect: true
sudo: false
